version: '3'
services:
  shopbiz-ui:
    container_name: shopbiz-ui
    build: ./shopbiz-ui
    ports:
      - "80:80"
    depends_on:
      - shopbiz-api
    networks:
      - shopbiz-network

  shopbiz-api:
    container_name: shopbiz-api    
    build:
      context: shopbiz-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    # command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    depends_on:
      - mp-mysql
    networks:
      - shopbiz-network

  mp-mysql:
    container_name: mp-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: shopbiz
      MYSQL_ROOT_PASSWORD: taco
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    restart: always
    networks:
      - shopbiz-network

volumes:
  db-data:
networks:
  shopbiz-network: