spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(bioezBIYbRPEKz9C0NCPVDSpiDRl2B/YYJCPkEOwHVI=)
    password: ENC(mlWGlte635NuZLgDOv7vwAJLboy6GohH)
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

